title: Konveyor Engineering Knowledgebase
baseURL: "https://konveyor-eng-kbase.netlify.app/"
languageCode: en-us
theme: PaperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Archive
      url: archives
      weight: 10
taxonomies:
  tag: tags
