title: Konveyor Engineering Knowledgebase
baseURL: "https://engineering.konveyor.io/"
languageCode: en-us
theme: PaperMod
outputs:
  home:
    - HTML
    - JSON
menu:
  main:
    - name: Search
      url: search
      weight: 5
    - name: Tags
      url: tags
      weight: 10
    - name: Authors
      url: authors
      weight: 10
    - name: Archive
      url: archives
      weight: 10
taxonomies:
  tag: tags
  author: authors
